const GAMES={"أونو":{min:2,max:8},"بلوت":{min:4,max:4},"جاكارو":{min:2,max:4},"لودو":{min:2,max:4},"مافيا":{min:4,max:16},"مونوبولي":{min:2,max:6},"كود نيمز":{min:2,max:10},"رووليت":{min:2,max:12}};
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function base(game,players){return {game,players,turnIndex:0,phase:"playing",winner:null,log:[],createdAt:new Date().toISOString()}}
function create(game,players){if(!GAMES[game])throw Error("اللعبة غير مدعومة");const s=base(game,players);if(game==="أونو"){const d=[];for(const c of ["red","yellow","green","blue"]){for(let n=0;n<10;n++)d.push({c,n});for(let n=1;n<10;n++)d.push({c,n})}for(let i=0;i<8;i++)d.push({c:"wild",n:4});shuffle(d);s.deck=d;s.discard=[s.deck.pop()];s.hands={};players.forEach(p=>s.hands[p]=s.deck.splice(0,7))}else if(game==="لودو"||game==="جاكارو"){s.pieces=Object.fromEntries(players.map(p=>[p,[0,0,0,0]]));s.dice=null}else if(game==="مونوبولي"){s.money=Object.fromEntries(players.map(p=>[p,1500]));s.position=Object.fromEntries(players.map(p=>[p,0]));s.properties={};s.dice=null}else if(game==="مافيا"){const roles={};players.forEach(p=>roles[p]="citizen");shuffle(players.slice()).slice(0,Math.max(1,Math.floor(players.length/4))).forEach(p=>roles[p]="mafia");s.roles=roles;s.alive=Object.fromEntries(players.map(p=>[p,true]));s.votes={};s.phase="night"}else if(game==="كود نيمز"){s.words=shuffle(["بحر","قمر","ملاذ","نار","ملك","ورد","سيف","باب","ذهب","نجم","مفتاح","عين","كتاب","شمس","نهر","قصر","برج","مطر","طائرة","موز"]);s.teams=Object.fromEntries(players.map((p,i)=>[p,i%2?"blue":"red"]));s.revealed={};s.clue=null;s.teamTurn="red"}else if(game==="بلوت"){s.hands=Object.fromEntries(players.map(p=>[p,[]]));s.trick=[];s.scores=Object.fromEntries(players.map(p=>[p,0]))}else if(game==="رووليت"){s.bets={};s.result=null}return s}
function player(s,user){if(!s.players.includes(user))throw Error("لست لاعبًا")}
function turn(s,user){player(s,user);if(s.players[s.turnIndex]!==user)throw Error("ليس دورك")}
function advance(s){s.turnIndex=(s.turnIndex+1)%s.players.length}
function act(s,user,a){if(s.phase!=="playing")throw Error("انتهت اللعبة");player(s,user);a=a||{};if(s.game!=="مافيا"&&s.game!=="كود نيمز")turn(s,user);switch(s.game){case "أونو":return uno(s,user,a);case "لودو":return board(s,user,a);case "جاكارو":return board(s,user,a);case "مونوبولي":return monopoly(s,user,a);case "مافيا":return mafia(s,user,a);case "كود نيمز":return codenames(s,user,a);case "بلوت":return baloot(s,user,a);case "رووليت":return roulette(s,user,a)}throw Error("حركة غير مدعومة")}
function uno(s,u,a){if(a.type==="draw"){if(!s.deck.length)throw Error("لا توجد أوراق");s.hands[u].push(s.deck.pop());return s}if(a.type!=="play")throw Error("حركة غير صالحة");const h=s.hands[u],i=Number(a.index),c=h[i],top=s.discard.at(-1);if(!c)throw Error("ورقة غير موجودة");if(c.c!=="wild"&&top.c!=="wild"&&c.c!==top.c&&c.n!==top.n)throw Error("الورقة غير صالحة");h.splice(i,1);s.discard.push(c);if(!h.length){s.winner=u;s.phase="finished"}else advance(s);return s}
function board(s,u,a){if(a.type==="roll"){s.dice=1+Math.floor(Math.random()*6);return s}if(a.type!=="move")throw Error("حركة غير صالحة");const i=Number(a.piece);if(!s.dice||i<0||i>3)throw Error("حجر غير صالح");s.pieces[u][i]+=s.dice;s.dice=null;if(s.pieces[u][i]>=57){s.winner=u;s.phase="finished"}else advance(s);return s}
function monopoly(s,u,a){if(a.type==="roll"){s.dice=2+Math.floor(Math.random()*11);s.position[u]=(s.position[u]+s.dice)%40;s.money[u]-=25;advance(s);return s}if(a.type==="buy"){const p=s.position[u],price=100+p*10;if(s.properties[p])throw Error("الموقع مملوك");if(s.money[u]<price)throw Error("الرصيد لا يكفي");s.money[u]-=price;s.properties[p]=u;return s}throw Error("حركة غير صالحة")}
function mafia(s,u,a){if(s.phase==="night"){if(s.roles[u]!=="mafia"||a.type!=="kill")throw Error("صلاحية غير متاحة");s.nightTarget=a.target;s.phase="day";return s}if(a.type!=="vote")throw Error("التصويت غير متاح");s.votes[u]=a.target;const alive=s.players.filter(p=>s.alive[p]);if(Object.keys(s.votes).length>=alive.length){const c={};Object.values(s.votes).forEach(x=>c[x]=(c[x]||0)+1);const dead=Object.entries(c).sort((x,y)=>y[1]-x[1])[0]?.[0];if(dead)s.alive[dead]=false;s.votes={};s.phase="night"}return s}
function codenames(s,u,a){const team=s.teams[u];if(a.type==="clue"){if(u!==s.players.find(p=>s.teams[p]===team))throw Error("القائد فقط");s.clue={text:String(a.text||""),count:Number(a.count)||0};s.teamTurn=team;return s}if(a.type!=="guess")throw Error("التخمين غير متاح");const i=Number(a.index);if(!s.words[i])throw Error("كلمة غير صالحة");s.revealed[i]=team;s.teamTurn=team==="red"?"blue":"red";s.clue=null;return s}
function baloot(s,u,a){if(a.type==="deal"){const deck=[];for(const suit of ["♠","♥","♦","♣"])for(let n=1;n<=13;n++)deck.push({suit,rank:n});shuffle(deck);s.players.forEach(p=>s.hands[p]=deck.splice(0,8));return s}if(a.type!=="play")throw Error("حركة غير صالحة");const i=Number(a.index),card=s.hands[u][i];if(!card)throw Error("ورقة غير صالحة");s.hands[u].splice(i,1);s.trick.push({user:u,card});if(s.trick.length===s.players.length){s.scores[s.trick[0].user]++;s.trick=[]}advance(s);return s}
function roulette(s,u,a){if(a.type!=="bet")throw Error("الحركة غير صالحة");s.bets[u]={choice:String(a.choice||"red"),amount:Math.max(1,Number(a.amount)||1)};advance(s);return s}
function publicState(s,u){const x=JSON.parse(JSON.stringify(s));if(s.game==="أونو")x.hands=Object.fromEntries(Object.entries(s.hands).map(([p,h])=>[p,p===u?h:h.map(()=>({hidden:true}))]));if(s.game==="بلوت")x.hands=Object.fromEntries(Object.entries(s.hands).map(([p,h])=>[p,p===u?h:h.map(()=>({hidden:true}))]));if(s.game==="مافيا")x.roles={[u]:s.roles[u]};return x}
module.exports={GAMES,create,act,publicState};
