"use strict";
require("dotenv").config();
const path=require("path");
const fs=require("fs");
const crypto=require("crypto");
const express=require("express"),cors=require("cors"),helmet=require("helmet");
const bcrypt=require("bcryptjs");
const {Client,GatewayIntentBits,EmbedBuilder,PermissionFlagsBits,ChannelType}=require("discord.js");

const app=express(), PORT=Number(process.env.PORT||3000), DATA=path.join(__dirname,"data.json");
app.disable("x-powered-by"); app.use(helmet({contentSecurityPolicy:false})); app.use(cors({origin:true,credentials:true}));
app.use(express.json({limit:"100kb"})); app.use(express.static(path.join(__dirname,"public")));
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildPresences,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildVoiceStates]});

const roleIds=["1530712642384040027","1521187079336362024","1531109479264026706","1548732297669255259","1548732341185155103","1548732606508703744"];
const roleNames={}; const sessions=new Map(), verifyCodes=new Map(), activity=new Map(), voice=new Map(); let visits=0;
const empty={users:[],reviews:[],groups:[],groupRequests:[],tickets:[],applications:[],applicationQuestions:["عرفنا بنفسك.","ما خبرتك في الإدارة؟","لماذا ترغب بالانضمام؟"],cinema:[],games:[],messages:[],privateChats:[],logs:[],subscriptions:[],admins:[],settings:{announcement:"أهلاً بكم في MLD Community",announcementColor:"#ff9cdc"}};
function db(){try{return JSON.parse(fs.readFileSync(DATA,"utf8"))}catch{return JSON.parse(JSON.stringify(empty))}}
let store=db();
function save(){fs.writeFileSync(DATA,JSON.stringify(store,null,2))}
function logEvent(req,type,data={}){
  try{
    const body={...data};
    for(const k of ["password","token","code"])if(k in body)body[k]="[hidden]";
    store.logs.unshift({id:id(),type,path:req?.path||"",method:req?.method||"",userId:req?.user?.id||null,userName:req?.user?.displayName||null,data,at:new Date().toISOString()});
    store.logs=store.logs.slice(0,10000);save();
  }catch{}
}
app.use("/api",(req,res,next)=>{const original=req.body;res.on("finish",()=>{req.user=req.user||current(req);if(req.path.startsWith("/auth/login")||req.path.startsWith("/auth/register")||req.path.startsWith("/auth/verify"))return;logEvent(req,"api",{status:res.statusCode,body:{...original,password:undefined,code:undefined}})});next()});
function id(){return crypto.randomBytes(9).toString("hex")}
function token(){return crypto.randomBytes(32).toString("hex")}
function safeUser(u){return {id:u.id,username:u.username,discordUsername:u.discordUsername,displayName:u.displayName,role:u.role,avatar:u.avatar,bio:u.bio||"",disabled:!!u.disabled}}
function current(req){const t=req.headers.authorization?.replace(/^Bearer\s+/,"");return t?sessions.get(t)||null:null}
function requireAuth(req,res,next){const u=current(req);if(!u)return res.status(401).json({error:"سجّل الدخول أولاً"});req.user=u;next()}
function requireOwner(req,res,next){if(!req.user||req.user.role!=="owner")return res.status(403).json({error:"هذا الإجراء للمالك فقط"});next()}
function requireAdmin(req,res,next){if(!req.user||!["owner","admin"].includes(req.user.role))return res.status(403).json({error:"ليس لديك صلاحية الإدارة"});next()}
function validName(x){return /^[A-Za-z0-9_\u0600-\u06FF.-]{3,24}$/.test(String(x||""))}
function getActivity(uid){if(!activity.has(uid))activity.set(uid,{messages:0,mentionsReceived:0,voiceMinutes:0,voiceJoins:0});return activity.get(uid)}
async function guild(){if(!client.isReady())throw Error("Discord bot is not ready");return client.guilds.fetch(process.env.DISCORD_GUILD_ID)}
async function members(){return (await guild()).members.fetch()}
async function findDiscord(name){const g=await guild(),m=await g.members.fetch();const q=String(name).replace(/^@/,"").toLowerCase();return [...m.values()].find(x=>x.user.username.toLowerCase()===q||x.displayName.toLowerCase()===q||x.user.globalName?.toLowerCase()===q)||null}
function memberJson(m){const roles=[...m.roles.cache.values()].filter(r=>r.id!==m.guild.id).sort((a,b)=>b.position-a.position);const lead=roles.find(r=>roleIds.includes(r.id));return{id:m.id,name:m.displayName,username:m.user.username,globalName:m.user.globalName,avatar:m.displayAvatarURL({extension:"png",size:256}),joinedAt:m.joinedAt,rank:lead?.name||roles[0]?.name||"عضو",roles:roles.map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position})),importantRoles:roles.filter(r=>roleIds.includes(r.id)).map(r=>({id:r.id,name:r.name,color:r.hexColor})),stats:getActivity(m.id)}}

app.get("/health",(q,s)=>s.json({ok:true,botReady:client.isReady(),uptimeSeconds:Math.floor(process.uptime()),visits}));
app.get("/api/public/server",async(q,s)=>{visits++;try{const g=await guild();s.json({id:g.id,name:g.name,icon:g.iconURL({extension:"png",size:256}),memberCount:g.memberCount,online:[...g.presences.cache.values()].filter(p=>["online","idle","dnd"].includes(p.status)).length,visits,ownerName:process.env.OWNER_DISPLAY_NAME||"فهد المطيري",invite:process.env.DISCORD_INVITE_URL||""})}catch(e){s.status(503).json({error:"Discord server unavailable"})}});
app.get("/api/public/members",async(q,s)=>{try{const all=await members(),x=String(q.query.q||"").toLowerCase().replace(/^@/,""),a=[...all.values()].filter(m=>!x||[m.displayName,m.user.username,m.user.globalName,m.id].filter(Boolean).join(" ").toLowerCase().includes(x)).sort((a,b)=>b.roles.highest.position-a.roles.highest.position);s.json({members:a.map(memberJson),total:a.length,totalServerMembers:all.size})}catch(e){s.status(503).json({error:"الأعضاء غير متاحين حالياً"})}});
app.get("/api/public/member/:id",async(q,s)=>{try{const m=await(await guild()).members.fetch(q.params.id);s.json(memberJson(m))}catch{s.status(404).json({error:"العضو غير موجود"})}});
app.get("/api/public/roles",async(q,s)=>{try{const g=await guild(),ms=await members();s.json({roles:roleIds.map(x=>g.roles.cache.get(x)).filter(Boolean).map(r=>({...r.toJSON(),membersCount:[...ms.values()].filter(m=>m.roles.cache.has(r.id)).length,color:r.hexColor,permissions:r.permissions.toArray()}))})}catch{s.status(503).json({error:"الرتب غير متاحة"})}});
app.get("/api/public/roles/:id/members",async(q,s)=>{try{const g=await guild(),r=g.roles.cache.get(q.params.id);if(!r||!roleIds.includes(r.id))return s.status(404).json({error:"الرتبة غير موجودة"});const ms=(await members());s.json({role:{id:r.id,name:r.name,color:r.hexColor,membersCount:[...ms.values()].filter(m=>m.roles.cache.has(r.id)).length},members:[...ms.values()].filter(m=>m.roles.cache.has(r.id)).map(memberJson)})}catch{s.status(503).json({error:"تعذر تحميل أعضاء الرتبة"})}});
app.get("/api/public/top",async(q,s)=>{try{const ms=await members(),a=[...ms.values()].map(memberJson),sort=k=>[...a].sort((x,y)=>(y.stats[k]||0)-(x.stats[k]||0)).slice(0,10);s.json({messages:sort("messages"),mentions:sort("mentionsReceived"),voice:sort("voiceMinutes"),joins:sort("voiceJoins")})}catch{s.status(503).json({error:"TOP غير متاح"})}});

app.get("/api/settings",async(q,s)=>s.json({announcement:store.settings.announcement,announcementColor:store.settings.announcementColor}));
app.get("/api/auth/me",(q,s)=>{const u=current(q);s.json({user:u?safeUser(u):null})});
app.post("/api/auth/register",async(q,s)=>{try{const {username,password,discordUsername}=q.body||{};if(!validName(username)||String(password||"").length<8||!discordUsername)return s.status(400).json({error:"أدخل اسم مستخدم وكلمة مرور 8 أحرف على الأقل واسم Discord"});if(store.users.some(x=>x.username.toLowerCase()===username.toLowerCase()))return s.status(409).json({error:"اسم المستخدم مستخدم"});const m=await findDiscord(discordUsername);if(!m)return s.status(400).json({error:"حساب Discord غير موجود في السيرفر"});if(store.users.some(x=>x.discordId===m.id))return s.status(409).json({error:"هذا Discord مرتبط بحساب موقع بالفعل"});const code=String(Math.floor(100000+Math.random()*900000));verifyCodes.set(code,{username,password,discordUsername,discordId:m.id,avatar:m.displayAvatarURL({extension:"png",size:256}),expires:Date.now()+10*60e3});await m.send({embeds:[new EmbedBuilder().setTitle("MLD · تأكيد الحساب").setDescription("رمز تأكيد حساب الموقع: **"+code+"**\nلا تشاركه مع أي شخص.").setColor("#ff9cdc")]}).catch(()=>{throw Error("تعذر إرسال الخاص؛ فعّل الرسائل الخاصة من أعضاء السيرفر")});s.json({ok:true,verificationRequired:true,message:"تم إرسال رمز التحقق إلى Discord الخاص بك"})}catch(e){s.status(400).json({error:e.message||"تعذر إنشاء الحساب"})}});
app.post("/api/auth/verify",async(q,s)=>{const code=String(q.body?.code||"");const v=verifyCodes.get(code);if(!v||v.expires<Date.now())return s.status(400).json({error:"رمز التحقق غير صحيح أو منتهي"});verifyCodes.delete(code);const u={id:id(),username:v.username,password:await bcrypt.hash(v.password,12),discordUsername:v.discordUsername,discordId:v.discordId,displayName:v.username,role:"member",avatar:v.avatar,createdAt:new Date().toISOString()};store.users.push(u);save();const t=token();sessions.set(t,safeUser(u));s.json({token:t,user:safeUser(u)})});
app.post("/api/auth/login",async(q,s)=>{const {username,password}=q.body||{};let u=store.users.find(x=>x.username.toLowerCase()===String(username||"").toLowerCase());if(!u&&username===(process.env.OWNER_USERNAME||"w4px")&&process.env.OWNER_PASSWORD)u={id:"owner",username:process.env.OWNER_USERNAME||"w4px",displayName:process.env.OWNER_DISPLAY_NAME||"فهد المطيري",role:"owner",avatar:process.env.OWNER_AVATAR||"",password:await bcrypt.hash(process.env.OWNER_PASSWORD,12)};if(!u||u.disabled||!(await bcrypt.compare(String(password||""),u.password)))return s.status(401).json({error:"بيانات الدخول غير صحيحة"});const t=token(),su=safeUser(u);sessions.set(t,su);s.json({token:t,user:su})});
app.post("/api/auth/logout",requireAuth,(q,s)=>{for(const [k,v] of sessions)if(v.id===q.user.id)sessions.delete(k);s.json({ok:true})});
app.patch("/api/auth/profile",requireAuth,(q,s)=>{const u=store.users.find(x=>x.id===q.user.id);if(!u)return s.status(404).json({error:"الحساب غير موجود"});if(q.body?.displayName!==undefined)u.displayName=String(q.body.displayName).trim().slice(0,40)||u.displayName;if(q.body?.bio!==undefined)u.bio=String(q.body.bio).slice(0,300);if(q.body?.avatar!==undefined)u.avatar=String(q.body.avatar).slice(0,500);save();const su=safeUser(u);for(const [k,v] of sessions)if(v.id===u.id)sessions.set(k,su);s.json(su)});
app.delete("/api/auth/account",requireAuth,(q,s)=>{if(q.user.role==="owner")return s.status(400).json({error:"لا يمكن حذف حساب المالك"});store.users=store.users.filter(x=>x.id!==q.user.id);for(const [k,v] of sessions)if(v.id===q.user.id)sessions.delete(k);save();s.json({ok:true})});

app.get("/api/reviews",(q,s)=>s.json(store.reviews.filter(x=>!x.hidden)));
app.post("/api/reviews",(q,s)=>{const u=current(q);const text=String(q.body?.text||"").trim();const rating=Math.max(1,Math.min(5,Number(q.body?.rating||5)));if(text.length<3||text.length>500)return s.status(400).json({error:"الرأي يجب أن يكون بين 3 و500 حرف"});const r={id:id(),userId:u?.id||null,name:u?.displayName||"زائر",text,rating,createdAt:new Date().toISOString()};store.reviews.unshift(r);save();s.json(r)});
app.delete("/api/reviews/:id",requireAuth,requireOwner,(q,s)=>{store.reviews=store.reviews.filter(x=>x.id!==q.params.id);save();s.json({ok:true})});

app.get("/api/groups",(q,s)=>s.json(store.groups.filter(x=>x.status==="approved")));
app.post("/api/groups",requireAuth,async(q,s)=>{const name=String(q.body?.name||"").trim(),desc=String(q.body?.description||"").trim();if(!name||!desc)return s.status(400).json({error:"أدخل اسم ووصف القروب"});const g={id:id(),name,description:desc,ownerId:q.user.id,ownerName:q.user.displayName,status:"pending",createdAt:new Date().toISOString()};store.groups.push(g);save();s.json(g)});
app.post("/api/groups/:id/join",requireAuth,async(q,s)=>{const g=store.groups.find(x=>x.id===q.params.id&&x.status==="approved");if(!g)return s.status(404).json({error:"القروب غير موجود"});if(store.groupRequests.some(x=>x.groupId===g.id&&x.userId===q.user.id&&x.status==="pending"))return s.status(409).json({error:"لديك طلب قائم"});const r={id:id(),groupId:g.id,userId:q.user.id,name:q.user.displayName,status:"pending",createdAt:new Date().toISOString()};store.groupRequests.push(r);save();const owner=store.users.find(x=>x.id===g.ownerId);if(owner?.discordId){const m=await (await guild()).members.fetch(owner.discordId).catch(()=>null);if(m)await m.send("لديك طلب انضمام جديد إلى قروب "+g.name).catch(()=>{})}s.json(r)});
app.get("/api/admin/groups",requireAuth,requireAdmin,(q,s)=>s.json({groups:store.groups,requests:store.groupRequests}));
app.post("/api/admin/groups/:id/status",requireAuth,requireAdmin,async(q,s)=>{const g=store.groups.find(x=>x.id===q.params.id);if(!g)return s.status(404).json({error:"القروب غير موجود"});const status=q.body?.status;if(!["approved","rejected"].includes(status))return s.status(400).json({error:"حالة غير صحيحة"});g.status=status;if(status==="approved"&&!g.discordCategoryId){try{const gd=await guild(),role=await gd.roles.create({name:"MLD · "+g.name,reason:"MLD group"}),cat=await gd.channels.create({name:"قروب・"+g.name,type:ChannelType.GuildCategory}),txt=await gd.channels.create({name:"دردشة・"+g.name,type:ChannelType.GuildText,parent:cat.id}),vc=await gd.channels.create({name:"صوت・"+g.name,type:ChannelType.GuildVoice,parent:cat.id});g.discordCategoryId=cat.id;g.discordRoleId=role.id;g.discordTextId=txt.id;g.discordVoiceId=vc.id;const owner=store.users.find(x=>x.id===g.ownerId);if(owner?.discordId){const om=await gd.members.fetch(owner.discordId).catch(()=>null);if(om)await om.roles.add(role).catch(()=>{});await om?.send("تم قبول قروبك وإنشاؤه في سيرفر MLD: "+g.name).catch(()=>{})}}catch(e){console.error("Group provisioning:",e)}}else if(status==="rejected"){const owner=store.users.find(x=>x.id===g.ownerId);if(owner?.discordId){const gd=await guild().catch(()=>null);const om=gd?await gd.members.fetch(owner.discordId).catch(()=>null):null;await om?.send("تم رفض طلب إنشاء قروبك: "+g.name).catch(()=>{})}}save();s.json(g)});
app.post("/api/admin/groups/requests/:id/status",requireAuth,requireAdmin,async(q,s)=>{const r=store.groupRequests.find(x=>x.id===q.params.id);if(!r)return s.status(404).json({error:"الطلب غير موجود"});const g=store.groups.find(x=>x.id===r.groupId);r.status=q.body?.status==="accepted"?"accepted":"rejected";if(r.status==="accepted"&&g?.discordRoleId){const m=await (await guild()).members.fetch(store.users.find(x=>x.id===r.userId)?.discordId).catch(()=>null);if(m)await m.roles.add(g.discordRoleId).catch(()=>{})}save();s.json(r)});
app.post("/api/groups/:id/requests/:rid/status",requireAuth,async(q,s)=>{
 const g=store.groups.find(x=>x.id===q.params.id); if(!g)return s.status(404).json({error:"القروب غير موجود"});
 if(g.ownerId!==q.user.id&&q.user.role!=="owner")return s.status(403).json({error:"مالك القروب فقط"});
 const r=store.groupRequests.find(x=>x.id===q.params.rid&&x.groupId===g.id); if(!r)return s.status(404).json({error:"طلب الانضمام غير موجود"});
 if(!["accepted","rejected"].includes(q.body?.status))return s.status(400).json({error:"حالة غير صحيحة"});
 r.status=q.body.status; const u=store.users.find(x=>x.id===r.userId);
 const m=u?.discordId?await (await guild()).members.fetch(u.discordId).catch(()=>null):null;
 if(r.status==="accepted"&&g.discordRoleId){if(m)await m.roles.add(g.discordRoleId).catch(()=>{});if(m)await m.send("تم قبول طلب انضمامك إلى قروب "+g.name+" في MLD.").catch(()=>{})}
 else if(r.status==="rejected"&&m)await m.send("تم رفض طلب انضمامك إلى قروب "+g.name+" في MLD.").catch(()=>{});
 save();s.json(r);
});

app.post("/api/tickets",requireAuth,(q,s)=>{const subject=String(q.body?.subject||"استفسار").trim(),message=String(q.body?.message||"").trim();if(!message)return s.status(400).json({error:"اكتب رسالتك"});const t={id:id(),userId:q.user.id,userName:q.user.displayName,subject,message,replies:[],status:"open",claimedBy:null,createdAt:new Date().toISOString()};store.tickets.unshift(t);save();s.json(t)});
app.get("/api/tickets",requireAuth,(q,s)=>s.json(q.user.role==="member"?store.tickets.filter(x=>x.userId===q.user.id):store.tickets));
app.post("/api/tickets/:id/reply",requireAuth,(q,s)=>{const t=store.tickets.find(x=>x.id===q.params.id);if(!t)return s.status(404).json({error:"التذكرة غير موجودة"});if(q.user.role==="member"&&t.userId!==q.user.id)return s.status(403).json({error:"ممنوع"});const m=String(q.body?.message||"").trim();if(!m)return s.status(400).json({error:"اكتب الرد"});t.replies.push({id:id(),userId:q.user.id,name:q.user.displayName,message:m,at:new Date().toISOString()});save();s.json(t)});
app.post("/api/tickets/:id/claim",requireAuth,requireAdmin,(q,s)=>{const t=store.tickets.find(x=>x.id===q.params.id);if(!t)return s.status(404).json({error:"غير موجود"});t.claimedBy=q.user.id;save();s.json(t)});
app.post("/api/tickets/:id/close",requireAuth,requireAdmin,(q,s)=>{const t=store.tickets.find(x=>x.id===q.params.id);if(!t)return s.status(404).json({error:"غير موجود"});t.status="closed";save();s.json(t)});

app.get("/api/applications/questions",(q,s)=>s.json({questions:store.applicationQuestions}));
app.post("/api/applications",requireAuth,async(q,s)=>{if(q.user.role==="admin")return s.status(403).json({error:"التقديم متاح للمالك فقط من ناحية الإدارة"});const answers=Array.isArray(q.body?.answers)?q.body.answers:[];if(answers.length<store.applicationQuestions.length)return s.status(400).json({error:"أكمل جميع الأسئلة"});const a={id:id(),userId:q.user.id,name:q.user.displayName,discordUsername:q.user.discordUsername,answers,status:"pending",createdAt:new Date().toISOString()};store.applications.push(a);save();s.json(a)});
app.get("/api/owner/applications",requireAuth,requireOwner,(q,s)=>s.json(store.applications));
app.get("/api/admin/applications",requireAuth,requireOwner,(q,s)=>s.json(store.applications));
app.patch("/api/applications/:id/status",requireAuth,requireOwner,async(q,s)=>{const a=store.applications.find(x=>x.id===q.params.id);if(!a)return s.status(404).json({error:"غير موجود"});a.status=["accepted","rejected","pending"].includes(q.body?.status)?q.body.status:a.status;if(a.status==="accepted"){const u=store.users.find(x=>x.id===a.userId);const m=await (await guild()).members.fetch(u?.discordId).catch(()=>null);const adminRole=process.env.ADMIN_ROLE_ID||"1548732606508703744";if(m){await m.roles.add(adminRole).catch(()=>{});await m.send("تم قبول طلبك في إدارة MLD، وتم منحك رتبة Junior Staff.").catch(()=>{})}}else if(a.status==="rejected"){const u=store.users.find(x=>x.id===a.userId);const m=await (await guild()).members.fetch(u?.discordId).catch(()=>null);await m?.send("تم رفض طلب التقديم للإدارة في MLD.").catch(()=>{})}save();s.json(a)});
app.patch("/api/owner/questions",requireAuth,requireOwner,(q,s)=>{if(!Array.isArray(q.body?.questions)||!q.body.questions.length)return s.status(400).json({error:"أضف سؤالاً واحداً على الأقل"});store.applicationQuestions=q.body.questions.map(String).filter(x=>x.trim()).slice(0,15);save();s.json({questions:store.applicationQuestions})});

app.get("/api/chat",requireAuth,(q,s)=>s.json(store.messages.slice(-100)));
app.get("/api/chat/users",requireAuth,(q,s)=>s.json(store.users.filter(x=>x.id!==q.user.id&&!x.disabled).map(safeUser)));
app.get("/api/chat/private",requireAuth,(q,s)=>s.json(store.privateChats.filter(x=>x.members.includes(q.user.id)).map(x=>({...x,messages:x.messages.slice(-100)}))));
app.post("/api/chat/private",requireAuth,(q,s)=>{const members=[q.user.id,...(Array.isArray(q.body?.members)?q.body.members:[])].map(String);const unique=[...new Set(members)].filter(Boolean);if(unique.length<2||unique.length>20)return s.status(400).json({error:"اختر من 1 إلى 19 شخصاً"});const known=store.users.filter(x=>unique.includes(x.id)).map(x=>x.id);if(known.length!==unique.length)return s.status(400).json({error:"يوجد حساب غير صالح"});const c={id:id(),name:String(q.body?.name||"محادثة خاصة").slice(0,60),ownerId:q.user.id,members:unique,messages:[],createdAt:new Date().toISOString()};store.privateChats.unshift(c);save();s.json(c)});
app.get("/api/chat/private/:id",requireAuth,(q,s)=>{const c=store.privateChats.find(x=>x.id===q.params.id&&x.members.includes(q.user.id));if(!c)return s.status(404).json({error:"المحادثة غير موجودة"});s.json(c)});
app.post("/api/chat/private/:id/message",requireAuth,(q,s)=>{const c=store.privateChats.find(x=>x.id===q.params.id&&x.members.includes(q.user.id));if(!c)return s.status(404).json({error:"المحادثة غير موجودة"});const m=String(q.body?.message||"").trim();if(!m)return s.status(400).json({error:"اكتب رسالة"});c.messages.push({id:id(),userId:q.user.id,name:q.user.displayName,message:m,at:new Date().toISOString()});c.updatedAt=new Date().toISOString();save();s.json(c)});
app.post("/api/chat/private/:id/members",requireAuth,(q,s)=>{const c=store.privateChats.find(x=>x.id===q.params.id&&x.ownerId===q.user.id);if(!c)return s.status(403).json({error:"مالك المحادثة فقط"});const uid=String(q.body?.userId||"");if(!store.users.some(x=>x.id===uid))return s.status(404).json({error:"الحساب غير موجود"});if(!c.members.includes(uid))c.members.push(uid);save();s.json(c)});
app.delete("/api/chat/private/:id/members/:uid",requireAuth,(q,s)=>{const c=store.privateChats.find(x=>x.id===q.params.id&&x.ownerId===q.user.id);if(!c)return s.status(403).json({error:"مالك المحادثة فقط"});if(q.params.uid===c.ownerId)return s.status(400).json({error:"لا يمكن حذف مالك المحادثة"});c.members=c.members.filter(x=>x!==q.params.uid);save();s.json(c)});

app.post("/api/chat",requireAuth,(q,s)=>{const message=String(q.body?.message||"").trim();if(!message||message.length>1000)return s.status(400).json({error:"رسالة غير صالحة"});store.messages.push({id:id(),userId:q.user.id,name:q.user.displayName,message,at:new Date().toISOString()});save();s.json({ok:true})});

app.post("/api/zajel",requireAuth,async(q,s)=>{try{const m=await findDiscord(q.body?.discordUsername||"");if(!m)return s.status(404).json({error:"لم يتم العثور على العضو"});const text=String(q.body?.message||"").trim();if(!text||text.length>1000)return s.status(400).json({error:"اكتب الرسالة"});const named=q.body?.named!==false;const sender=named?("رسالة من "+q.user.displayName):"رسالة من مجهول";await m.send({content:sender+"\n\n"+text});logEvent(q,"zajel",{toDiscordId:m.id,toUsername:m.user.username,message:text,named});s.json({ok:true})}catch(e){s.status(400).json({error:e.message||"تعذر إرسال الزاجل"})}});
app.get("/api/owner/logs",requireAuth,requireOwner,(q,s)=>s.json(store.logs||[]));
app.get("/api/owner/zajel",requireAuth,requireOwner,(q,s)=>s.json((store.logs||[]).filter(x=>x.type==="zajel")));
app.get("/api/owner/accounts",requireAuth,requireOwner,(q,s)=>s.json(store.users.map(u=>({...safeUser(u),bio:u.bio||"",createdAt:u.createdAt}))));
app.delete("/api/owner/accounts/:id",requireAuth,requireOwner,(q,s)=>{if(q.params.id==="owner")return s.status(400).json({error:"لا يمكن حذف المالك"});store.users=store.users.filter(x=>x.id!==q.params.id);for(const [k,v] of sessions)if(v.id===q.params.id)sessions.delete(k);save();s.json({ok:true})});
app.post("/api/owner/subscriptions",requireAuth,requireOwner,(q,s)=>{const uid=String(q.body?.userId||"");if(!store.users.some(x=>x.id===uid))return s.status(404).json({error:"الحساب غير موجود"});const x={id:id(),userId:uid,bot:String(q.body?.bot||"").slice(0,80),active:q.body?.active!==false,features:Array.isArray(q.body?.features)?q.body.features.map(String).slice(0,30):[],at:new Date().toISOString()};store.subscriptions.push(x);save();s.json(x)});
app.patch("/api/owner/subscriptions/:id",requireAuth,requireOwner,(q,s)=>{const x=store.subscriptions.find(x=>x.id===q.params.id);if(!x)return s.status(404).json({error:"الاشتراك غير موجود"});if(q.body?.active!==undefined)x.active=!!q.body.active;save();s.json(x)});
app.get("/api/owner/subscriptions",requireAuth,requireOwner,(q,s)=>s.json(store.subscriptions||[]));
app.get("/api/owner/user/:id/private",requireAuth,requireOwner,(q,s)=>s.json((store.privateChats||[]).filter(x=>x.members.includes(q.params.id)).map(x=>({...x,messages:x.messages.slice(-200)}))));
app.post("/api/admin/dm",requireAuth,requireAdmin,async(q,s)=>{try{const m=await findDiscord(q.body?.discordUsername||"");if(!m)return s.status(404).json({error:"العضو غير موجود"});const msg=String(q.body?.message||"").trim();if(!msg)return s.status(400).json({error:"اكتب الرسالة"});await m.send({content:"من إدارة ملاذ | الاداري: <@"+q.user.id+">\n\n"+msg});logEvent(q,"admin_dm",{toDiscordId:m.id,toUsername:m.user.username,message:msg});s.json({ok:true})}catch(e){s.status(400).json({error:"تعذر إرسال الرسالة الخاصة"})}});
app.get("/api/cinema",(q,s)=>s.json(store.cinema));
app.post("/api/cinema",requireAuth,(q,s)=>{const title=String(q.body?.title||"").trim();if(!title)return s.status(400).json({error:"أدخل اسم المحتوى"});const x={id:id(),title,url:String(q.body?.url||"").trim(),ownerId:q.user.id,createdAt:new Date().toISOString()};store.cinema.push(x);save();s.json(x)});
app.delete("/api/cinema/:id",requireAuth,requireOwner,(q,s)=>{store.cinema=store.cinema.filter(x=>x.id!==q.params.id);save();s.json({ok:true})});

app.get("/api/games/sessions",(q,s)=>{const now=Date.now();store.games=store.games.filter(x=>now-new Date(x.updatedAt).getTime()<5*60e3&&x.status!=="ended");s.json(store.games)});
app.post("/api/games/sessions",requireAuth,(q,s)=>{const name=String(q.body?.game||"").trim();if(!name)return s.status(400).json({error:"اختر لعبة"});if(store.games.some(x=>x.players.some(p=>p.userId===q.user.id)))return s.status(409).json({error:"أنت داخل جلسة أخرى"});const g={id:id(),game:name,ownerId:q.user.id,ownerName:q.user.displayName,players:[{userId:q.user.id,name:q.user.displayName,role:null,team:null}],spectators:[],status:"waiting",min:Number(q.body?.min||2),max:Number(q.body?.max||20),state:{},updatedAt:new Date().toISOString()};store.games.push(g);save();s.json(g)});
app.post("/api/games/sessions/:id/join",requireAuth,(q,s)=>{const g=store.games.find(x=>x.id===q.params.id);if(!g)return s.status(404).json({error:"الجلسة غير موجودة"});if(store.games.some(x=>x.id!==g.id&&x.players.some(p=>p.userId===q.user.id)))return s.status(409).json({error:"أنت داخل جلسة أخرى"});if(g.players.length>=g.max)return s.status(400).json({error:"الجلسة ممتلئة"});g.players.push({userId:q.user.id,name:q.user.displayName,role:null,team:null});g.updatedAt=new Date().toISOString();save();s.json(g)});
app.post("/api/games/sessions/:id/leave",requireAuth,(q,s)=>{const g=store.games.find(x=>x.id===q.params.id);if(!g)return s.status(404).json({error:"الجلسة غير موجودة"});g.players=g.players.filter(p=>p.userId!==q.user.id);if(!g.players.length)store.games=store.games.filter(x=>x.id!==g.id);else g.updatedAt=new Date().toISOString();save();s.json({ok:true})});
app.post("/api/games/sessions/:id/start",requireAuth,(q,s)=>{const g=store.games.find(x=>x.id===q.params.id);if(!g)return s.status(404).json({error:"غير موجود"});if(g.ownerId!==q.user.id)return s.status(403).json({error:"منشئ الجلسة فقط"});g.status="active";g.updatedAt=new Date().toISOString();save();s.json(g)});

app.get("/api/owner/settings",requireAuth,requireOwner,(q,s)=>s.json(store.settings));
app.patch("/api/owner/settings",requireAuth,requireOwner,(q,s)=>{if(q.body?.announcement!==undefined)store.settings.announcement=String(q.body.announcement).slice(0,300);if(q.body?.announcementColor!==undefined)store.settings.announcementColor=String(q.body.announcementColor);save();s.json(store.settings)});
app.get("/api/owner/users",requireAuth,requireOwner,(q,s)=>s.json(store.users.map(safeUser)));
app.post("/api/owner/admins",requireAuth,requireOwner,(q,s)=>{const u=store.users.find(x=>x.id===q.body?.userId);if(!u)return s.status(404).json({error:"الحساب غير موجود"});u.role="admin";save();s.json(safeUser(u))});
app.delete("/api/owner/admins/:id",requireAuth,requireOwner,(q,s)=>{const u=store.users.find(x=>x.id===q.params.id);if(!u)return s.status(404).json({error:"غير موجود"});u.role="member";save();s.json(safeUser(u))});

app.use((req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
client.on("messageCreate",m=>{if(m.author.bot)return;getActivity(m.author.id).messages++;for(const u of m.mentions.users.values())if(!u.bot)getActivity(u.id).mentionsReceived++});
client.on("voiceStateUpdate",(o,n)=>{if(!o.channelId&&n.channelId){voice.set(n.id,Date.now());getActivity(n.id).voiceJoins++}if(o.channelId&&!n.channelId&&voice.has(n.id)){getActivity(n.id).voiceMinutes+=Math.round((Date.now()-voice.get(n.id))/60000);voice.delete(n.id)}});

app.listen(PORT,()=>console.log("MLD listening on "+PORT));
if(process.env.DISCORD_BOT_TOKEN&&process.env.DISCORD_GUILD_ID){client.once("ready",()=>console.log("Discord: "+client.user.tag));client.login(process.env.DISCORD_BOT_TOKEN).catch(e=>console.error("Discord login:",e.message))}else console.error("Missing Discord environment variables");
