"use strict";
require("dotenv").config();
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const express=require("express"),cors=require("cors"),helmet=require("helmet"),bcrypt=require("bcryptjs");
const {Client,GatewayIntentBits,ChannelType,PermissionFlagsBits}=require("discord.js");
const app=express(); app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:"1mb"}));
const PORT=Number(process.env.PORT||3000), DATA=path.join(__dirname,"data.json");
const IDS={owner:process.env.OWNER_ROLE_ID||"1530712642384040027",coowner:process.env.COOWNER_ROLE_ID||"1521187079336362024",founder:process.env.FOUNDER_ROLE_ID||"1531109479264026706",senior:process.env.SENIOR_STAFF_ROLE_ID||"1548732297669255259",staff:process.env.STAFF_ROLE_ID||"1548732341185155103",junior:process.env.JUNIOR_STAFF_ROLE_ID||"1548732606508703744"};
const base={users:[],sessions:[],reviews:[],chat:[],privateChats:[],tickets:[],applications:[],groups:[],zajel:[],games:[],logs:[],subscriptions:[],settings:{announcement:"مرحباً بكم في MLD · Community",announcementColor:"#ff9cde"}};
let store=base;
try{if(fs.existsSync(DATA))store=Object.assign(base,JSON.parse(fs.readFileSync(DATA,"utf8")))}catch{}
function save(){fs.writeFileSync(DATA,JSON.stringify(store,null,2))}
function id(){return crypto.randomUUID()}
function log(type,data){store.logs.unshift({id:id(),type,data,at:new Date().toISOString()});store.logs=store.logs.slice(0,3000);save()}
function cleanUser(u){if(!u)return null;return {id:u.id,username:u.username,displayName:u.displayName,avatar:u.avatar||"",bio:u.bio||"",role:u.role||"member",discordId:u.discordId||""}}
function auth(req,res,next){const t=(req.headers.authorization||"").replace(/^Bearer\s+/,"");const s=store.sessions.find(x=>x.token===t&&x.expires>Date.now());if(!s)return res.status(401).json({error:"تسجيل الدخول مطلوب"});req.user=store.users.find(x=>x.id===s.userId);if(!req.user)return res.status(401).json({error:"الحساب غير موجود"});next()}
function owner(req,res,next){if(req.user?.role!=="owner")return res.status(403).json({error:"هذه الصفحة للأونر فقط"});next()}
function admin(req,res,next){if(!["owner","admin"].includes(req.user?.role))return res.status(403).json({error:"صلاحية الإدارة مطلوبة"});next()}
async function discordMember(query){
 if(!guild)return null;
 try{await guild.members.fetch();const q=String(query||"").toLowerCase();return guild.members.cache.find(m=>m.id===query||m.user.username.toLowerCase()===q||m.user.tag.toLowerCase()===q||m.displayName.toLowerCase()===q)||null}catch{return null}
}
async function dmDiscord(member,text){try{if(member)await member.send(text);return true}catch{return false}}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildPresences]});
let guild=null;
client.once("ready",async()=>{guild=client.guilds.cache.get(process.env.DISCORD_GUILD_ID)||client.guilds.cache.first();console.log("MLD bot ready:",client.user.tag)})
if(process.env.DISCORD_BOT_TOKEN)client.login(process.env.DISCORD_BOT_TOKEN).catch(e=>console.error("Discord login failed",e.message));
app.get("/health",(q,s)=>s.json({ok:true,time:new Date().toISOString(),discord:!!guild}));
app.get("/api/public/server",async(q,s)=>{try{if(guild)await guild.members.fetch();s.json({name:guild?.name||"MLD Community",memberCount:guild?.memberCount||0,online:guild?[...guild.members.cache.values()].filter(m=>m.presence?.status&&m.presence.status!=="offline").length:0,visits:store.logs.filter(x=>x.type==="visit").length,ownerName:process.env.OWNER_DISPLAY_NAME||"فهد المطيري"})}catch{ s.json({name:"MLD Community",memberCount:0,online:0,visits:0,ownerName:"فهد المطيري"})}});
app.use((q,s,n)=>{if(q.path.startsWith("/api/")){if(q.method==="GET"&&q.path==="/api/public/server")return n();}if(q.method==="GET"&&!q.path.startsWith("/api"))log("visit",{path:q.path});n()});
app.get("/api/public/members",async(q,s)=>{try{if(guild)await guild.members.fetch();let a=guild?[...guild.members.cache.values()].filter(m=>!m.user.bot):[];const term=String(q.query.q||"").toLowerCase().trim();if(term)a=a.filter(m=>(m.displayName+" "+m.user.username+" "+m.id).toLowerCase().includes(term));a=a.sort((x,y)=>y.joinedTimestamp-x.joinedTimestamp);s.json({members:a.slice(0,100).map(m=>({id:m.id,name:m.displayName,username:m.user.username,avatar:m.displayAvatarURL({size:128}),importantRoles:m.roles.cache.filter(r=>IDS.owner===r.id||IDS.coowner===r.id||IDS.founder===r.id||IDS.senior===r.id||IDS.staff===r.id||IDS.junior===r.id).map(r=>({id:r.id,name:r.name}))}))})}catch(e){s.status(500).json({error:e.message})}});
app.get("/api/public/member/:id",async(q,s)=>{const m=await discordMember(q.params.id);if(!m)return s.status(404).json({error:"العضو غير موجود"});s.json({id:m.id,name:m.displayName,username:m.user.username,avatar:m.displayAvatarURL({size:256}),rank:m.roles.highest?.name||"Member",roles:m.roles.cache.filter(r=>r.id!==guild.id).map(r=>({id:r.id,name:r.name})),stats:{messages:store.logs.filter(x=>x.type==="message"&&x.data?.userId===m.id).length,mentionsReceived:0,voiceMinutes:0}})});
app.get("/api/public/roles",async(q,s)=>{if(!guild)return s.json({roles:[]});const wanted=new Set(Object.values(IDS));s.json({roles:[...guild.roles.cache.values()].filter(r=>wanted.has(r.id)).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,color:r.hexColor,membersCount:r.members.size}))})});
app.get("/api/public/roles/:id/members",async(q,s)=>{const r=guild?.roles.cache.get(q.params.id);if(!r)return s.status(404).json({error:"الرتبة غير موجودة"});s.json({role:{id:r.id,name:r.name,color:r.hexColor},members:[...r.members.values()].slice(0,100).map(m=>({id:m.id,name:m.displayName,avatar:m.displayAvatarURL({size:128})}))})});
app.get("/api/public/top",async(q,s)=>{const counts={};for(const x of store.logs.filter(x=>x.type==="message"))counts[x.data.userId]=(counts[x.data.userId]||0)+1;const ids=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10);const members=[];for(const [uid,n] of ids){const m=await discordMember(uid);if(m)members.push({id:m.id,name:m.displayName,avatar:m.displayAvatarURL({size:64}),stats:{messages:n}})}s.json({messages:members,voice:[],games:[]})});
app.post("/api/public/message",auth,async(q,s)=>{const m=await discordMember(q.body.discordUsername||q.body.discordId);if(!m)return s.status(404).json({error:"عضو Discord غير موجود"});const ok=await dmDiscord(m,q.body.message);log("dm",{userId:q.user.id,target:m.id});s.json({ok})});
app.post("/api/auth/register",async(q,s)=>{const {username,password,discordUsername}=q.body||{};if(!username||!password||!discordUsername||String(password).length<8)return s.status(400).json({error:"أكمل البيانات وكلمة المرور 8 أحرف على الأقل"});if(store.users.some(u=>u.username.toLowerCase()===String(username).toLowerCase()))return s.status(409).json({error:"اسم المستخدم مستخدم"});const m=await discordMember(discordUsername);if(!m)return s.status(400).json({error:"يجب أن تكون عضواً في سيرفر MLD"});if(store.users.some(u=>u.discordId===m.id))return s.status(409).json({error:"هذا Discord مرتبط بحساب موقع سابق"});const code=String(Math.floor(100000+Math.random()*900000));const u={id:id(),username:String(username),displayName:m.displayName,avatar:m.displayAvatarURL({size:256}),bio:"",role:"member",discordId:m.id,password:await bcrypt.hash(password,12),pendingCode:code,pendingUntil:Date.now()+10*60e3};store.users.push(u);await dmDiscord(m,"رمز تفعيل حساب MLD هو: "+code+"\\nينتهي خلال 10 دقائق.");log("register",{userId:u.id,discordId:m.id});save();s.json({ok:true})});
app.post("/api/auth/verify",async(q,s)=>{const u=store.users.find(x=>x.pendingCode===String(q.body.code||"")&&x.pendingUntil>Date.now());if(!u)return s.status(400).json({error:"الرمز غير صحيح أو منتهي"});delete u.pendingCode;delete u.pendingUntil;const token=id();store.sessions.push({token,userId:u.id,expires:Date.now()+30*864e5});save();s.json({token,user:cleanUser(u)})});
app.post("/api/auth/login",async(q,s)=>{const username=String(q.body.username||"");let u=store.users.find(x=>x.username.toLowerCase()===username.toLowerCase());if(!u&&username===(process.env.OWNER_USERNAME||"w4px")&&process.env.OWNER_PASSWORD)u={id:"owner",username,displayName:process.env.OWNER_DISPLAY_NAME||"فهد المطيري",role:"owner",avatar:process.env.OWNER_AVATAR||"",password:await bcrypt.hash(process.env.OWNER_PASSWORD,12)};if(!u||!(await bcrypt.compare(String(q.body.password||""),u.password)))return s.status(401).json({error:"بيانات الدخول غير صحيحة"});if(u.discordId&&!await discordMember(u.discordId))return s.status(403).json({error:"حسابك لم يعد عضواً في سيرفر MLD"});if(u.id==="owner"&&!store.users.some(x=>x.id==="owner"))store.users.push(u);const token=id();store.sessions.push({token,userId:u.id,expires:Date.now()+30*864e5});log("login",{userId:u.id});save();s.json({token,user:cleanUser(u)})});
app.get("/api/auth/me",auth,(q,s)=>s.json({user:cleanUser(q.user)}));
app.post("/api/auth/logout",auth,(q,s)=>{store.sessions=store.sessions.filter(x=>x.userId!==q.user.id);save();s.json({ok:true})});
app.patch("/api/auth/profile",auth,(q,s)=>{Object.assign(q.user,{displayName:String(q.body.displayName||q.user.displayName).slice(0,60),avatar:String(q.body.avatar||"").slice(0,500),bio:String(q.body.bio||"").slice(0,500)});save();s.json(cleanUser(q.user))});
app.get("/api/settings",(q,s)=>s.json(store.settings));
app.get("/api/chat",auth,(q,s)=>s.json(store.chat.slice(-100)));
app.post("/api/chat",auth,(q,s)=>{const message=String(q.body.message||"").trim();if(!message)return s.status(400).json({error:"اكتب رسالة"});const x={id:id(),userId:q.user.id,name:q.user.displayName,message:message.slice(0,1000),at:new Date().toISOString()};store.chat.push(x);log("message",{userId:q.user.discordId||q.user.id,message:x.message});save();s.json(x)});
app.get("/api/chat/users",auth,(q,s)=>s.json(store.users.filter(u=>u.id!==q.user.id).map(cleanUser)));
app.get("/api/chat/private",auth,(q,s)=>s.json(store.privateChats.filter(c=>c.members.includes(q.user.id)).map(c=>({id:c.id,name:c.name,ownerId:c.ownerId,members:c.members,messages:c.messages.slice(-3)}))));
app.post("/api/chat/private",auth,(q,s)=>{const members=[q.user.id,...(Array.isArray(q.body.members)?q.body.members:[])].filter((v,i,a)=>a.indexOf(v)===i).filter(v=>store.users.some(u=>u.id===v));if(members.length<2)return s.status(400).json({error:"اختر عضواً واحداً على الأقل"});const c={id:id(),name:String(q.body.name||"محادثة خاصة").slice(0,60),ownerId:q.user.id,members,messages:[]};store.privateChats.push(c);log("private_create",{chatId:c.id,ownerId:q.user.id,members});save();s.json(c)});
app.get("/api/chat/private/:id",auth,(q,s)=>{const c=store.privateChats.find(x=>x.id===q.params.id&&x.members.includes(q.user.id));if(!c)return s.status(404).json({error:"المحادثة غير موجودة"});s.json(c)});
app.post("/api/chat/private/:id/message",auth,(q,s)=>{const c=store.privateChats.find(x=>x.id===q.params.id&&x.members.includes(q.user.id));if(!c)return s.status(404).json({error:"المحادثة غير موجودة"});c.messages.push({id:id(),userId:q.user.id,name:q.user.displayName,message:String(q.body.message||"").slice(0,1000),at:new Date().toISOString()});save();s.json(c)});
app.post("/api/zajel",auth,async(q,s)=>{const m=await discordMember(q.body.discordUsername);if(!m)return s.status(404).json({error:"عضو Discord غير موجود"});const text=q.body.named?"رسالة من "+q.user.displayName+" (منشن):\\n"+q.body.message:"رسالة مجهولة من إدارة/مجتمع MLD:\\n"+q.body.message;const ok=await dmDiscord(m,text);if(!ok)return s.status(500).json({error:"تعذر إرسال الرسالة"});const z={id:id(),senderId:q.user.id,senderName:q.user.displayName,targetId:m.id,targetName:m.displayName,message:String(q.body.message||""),named:!!q.body.named,at:new Date().toISOString()};store.zajel.push(z);log("zajel",z);save();s.json({ok:true})});
app.get("/api/groups",async(q,s)=>s.json(store.groups.filter(g=>g.status==="approved").map(g=>({id:g.id,name:g.name,description:g.description,ownerName:g.ownerName}))));
app.post("/api/groups",auth,(q,s)=>{const g={id:id(),name:String(q.body.name||"قروب").slice(0,60),description:String(q.body.description||"").slice(0,1000),ownerId:q.user.id,ownerName:q.user.displayName,discordId:q.user.discordId,status:"pending",createdAt:new Date().toISOString()};store.groups.push(g);log("group_request",g);save();s.json(g)});
app.post("/api/groups/:id/join",auth,(q,s)=>{const g=store.groups.find(x=>x.id===q.params.id&&x.status==="approved");if(!g)return s.status(404).json({error:"القروب غير موجود"});g.requests=g.requests||[];if(!g.requests.includes(q.user.id))g.requests.push(q.user.id);log("group_join",{groupId:g.id,userId:q.user.id});save();s.json({ok:true})});
async function provisionGroup(g){if(!guild)return false;try{const role=await guild.roles.create({name:"MLD • "+g.name,reason:"MLD group"});const cat=await guild.channels.create({name:"◇ "+g.name,type:ChannelType.GuildCategory});const text=await guild.channels.create({name:"chat-"+g.name.toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,"-").slice(0,70),type:ChannelType.GuildText,parent:cat.id,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:role.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]}]});const voice=await guild.channels.create({name:"🔊 "+g.name,type:ChannelType.GuildVoice,parent:cat.id,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:role.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]}]});g.discord={roleId:role.id,categoryId:cat.id,textId:text.id,voiceId:voice.id};const m=await discordMember(g.discordId);if(m)await m.roles.add(role);return true}catch(e){log("group_error",{groupId:g.id,error:e.message});return false}}
app.get("/api/admin/groups",auth,owner,(q,s)=>s.json({groups:store.groups}));
app.post("/api/admin/groups/:id/status",auth,owner,async(q,s)=>{const g=store.groups.find(x=>x.id===q.params.id);if(!g)return s.status(404).json({error:"القروب غير موجود"});g.status=q.body.status==="approved"?"approved":"rejected";if(g.status==="approved"){const ok=await provisionGroup(g);if(!ok)return s.status(500).json({error:"تعذر إنشاء القروب في Discord"});const m=await discordMember(g.discordId);await dmDiscord(m,"تم قبول قروبك في MLD وتم إنشاء المجلد والشات والروم والرتبة.");}save();log("group_status",{groupId:g.id,status:g.status});s.json(g)});
app.get("/api/tickets",auth,(q,s)=>s.json(store.tickets.filter(t=>t.userId===q.user.id||["admin","owner"].includes(q.user.role))));
app.post("/api/tickets",auth,(q,s)=>{const t={id:id(),userId:q.user.id,userName:q.user.displayName,subject:String(q.body.subject||"بدون عنوان").slice(0,100),message:String(q.body.message||"").slice(0,2000),status:"open",replies:[],createdAt:new Date().toISOString()};store.tickets.push(t);log("ticket_create",t);save();s.json(t)});
app.post("/api/tickets/:id/reply",auth,(q,s)=>{const t=store.tickets.find(x=>x.id===q.params.id&&(x.userId===q.user.id||["admin","owner"].includes(q.user.role)));if(!t)return s.status(404).json({error:"التذكرة غير موجودة"});t.replies.push({id:id(),userId:q.user.id,name:q.user.displayName,message:String(q.body.message||"").slice(0,2000),at:new Date().toISOString()});save();log("ticket_reply",{ticketId:t.id,userId:q.user.id});s.json(t)});
app.post("/api/tickets/:id/close",auth,admin,(q,s)=>{const t=store.tickets.find(x=>x.id===q.params.id);if(!t)return s.status(404).json({error:"التذكرة غير موجودة"});t.status="closed";save();log("ticket_close",{ticketId:t.id,userId:q.user.id});s.json(t)});
app.get("/api/applications/questions",(q,s)=>s.json({questions:store.settings.questions||["عرّف بنفسك.","لماذا تريد الانضمام للإدارة؟","ما الذي ستضيفه لمجتمع MLD؟","كم تستطيع التواجد أسبوعياً؟"]}));
app.post("/api/applications",auth,(q,s)=>{const a={id:id(),userId:q.user.id,name:q.user.displayName,discordUsername:q.user.discordId,answers:q.body.answers||[],status:"pending",createdAt:new Date().toISOString()};store.applications.push(a);log("application",a);save();s.json(a)});
app.get("/api/owner/applications",auth,owner,(q,s)=>s.json(store.applications));
app.patch("/api/applications/:id/status",auth,owner,async(q,s)=>{const a=store.applications.find(x=>x.id===q.params.id);if(!a)return s.status(404).json({error:"التقديم غير موجود"});a.status=q.body.status==="accepted"?"accepted":"rejected";if(a.status==="accepted"){const m=await discordMember(a.discordUsername);if(m&&IDS.junior)await m.roles.add(IDS.junior).catch(()=>{});await dmDiscord(m,"تم قبول تقديمك للإدارة في MLD. أهلاً بك معنا.");}save();log("application_status",{applicationId:a.id,status:a.status});s.json(a)});
app.get("/api/reviews",(q,s)=>s.json(store.reviews));
app.post("/api/reviews",(q,s)=>{const r={id:id(),name:q.body.name||"عضو MLD",text:String(q.body.text||"").slice(0,1000),userId:q.user?.id||null,at:new Date().toISOString()};store.reviews.unshift(r);save();log("review",r);s.json(r)});
app.get("/api/cinema",(q,s)=>s.json(store.settings.cinema||[]));
app.get("/api/games/sessions",auth,(q,s)=>{store.games=store.games.filter(x=>Date.now()-x.createdAt<30*60e3&&!x.ended);save();s.json(store.games)});
app.post("/api/games/sessions",auth,(q,s)=>{if(store.games.some(g=>!g.ended&&g.players.some(p=>p.userId===q.user.id)))return s.status(409).json({error:"لديك جلسة نشطة بالفعل"});if(store.games.some(g=>!g.ended&&g.ownerId===q.user.id))return s.status(409).json({error:"لا يمكنك إنشاء أكثر من لعبة نشطة"});const g={id:id(),game:String(q.body.game||"Roulette"),ownerId:q.user.id,ownerName:q.user.displayName,min:Number(q.body.min||1),max:Number(q.body.max||20),players:[{userId:q.user.id,name:q.user.displayName}],createdAt:Date.now(),started:false,state:{}};store.games.push(g);save();s.json(g)});
app.post("/api/games/sessions/:id/join",auth,(q,s)=>{const g=store.games.find(x=>x.id===q.params.id&&!x.ended);if(!g)return s.status(404).json({error:"الجلسة غير موجودة"});if(g.players.some(p=>p.userId===q.user.id))return s.json(g);if(store.games.some(x=>!x.ended&&x.players.some(p=>p.userId===q.user.id)))return s.status(409).json({error:"أنت داخل لعبة أخرى"});if(g.players.length>=g.max)return s.status(409).json({error:"اللعبة ممتلئة"});g.players.push({userId:q.user.id,name:q.user.displayName});save();s.json(g)});
app.post("/api/games/sessions/:id/leave",auth,(q,s)=>{const g=store.games.find(x=>x.id===q.params.id&&!x.ended);if(!g)return s.json({ok:true});g.players=g.players.filter(p=>p.userId!==q.user.id);if(!g.players.length)g.ended=true;save();s.json(g)});
app.post("/api/games/sessions/:id/start",auth,(q,s)=>{const g=store.games.find(x=>x.id===q.params.id&&!x.ended);if(!g)return s.status(404).json({error:"الجلسة غير موجودة"});if(g.ownerId!==q.user.id)return s.status(403).json({error:"منشئ الجلسة فقط يبدأ اللعبة"});g.started=true;if(g.game==="Code Names"){const words=["قمر","بحر","مفتاح","ملك","نجم","صحراء","روبوت","تفاحة","قلعة","قطار","نار","مطر","ذهب","كتاب","عين","جسر","نمر","طائرة","ورد","موسيقى"];g.state={words,red:[],blue:[],turn:"red",clue:""}}save();s.json(g)});
app.get("/api/owner/logs",auth,owner,(q,s)=>s.json(store.logs));
app.get("/api/owner/zajel",auth,owner,(q,s)=>s.json(store.zajel));
app.get("/api/owner/accounts",auth,owner,(q,s)=>s.json(store.users.map(cleanUser)));
app.delete("/api/owner/accounts/:id",auth,owner,(q,s)=>{if(q.params.id==="owner")return s.status(400).json({error:"لا يمكن حذف الأونر"});store.users=store.users.filter(u=>u.id!==q.params.id);store.sessions=store.sessions.filter(x=>x.userId!==q.params.id);save();log("account_delete",{userId:q.params.id});s.json({ok:true})});
app.post("/api/owner/admins",auth,owner,(q,s)=>{const u=store.users.find(x=>x.id===q.body.userId);if(!u)return s.status(404).json({error:"الحساب غير موجود"});u.role="admin";save();log("admin_grant",{userId:u.id});s.json(cleanUser(u))});
app.delete("/api/owner/admins/:id",auth,owner,(q,s)=>{const u=store.users.find(x=>x.id===q.params.id);if(!u)return s.status(404).json({error:"الحساب غير موجود"});u.role="member";save();s.json(cleanUser(u))});
app.get("/api/owner/user/:id/private",auth,owner,(q,s)=>s.json(store.privateChats.filter(c=>c.members.includes(q.params.id))));
app.get("/api/owner/subscriptions",auth,owner,(q,s)=>s.json(store.subscriptions));
app.post("/api/owner/subscriptions",auth,owner,(q,s)=>{const x={id:id(),userId:q.body.userId,bot:q.body.bot,active:true,at:new Date().toISOString()};store.subscriptions.push(x);save();log("subscription",x);s.json(x)});
app.patch("/api/owner/subscriptions/:id",auth,owner,(q,s)=>{const x=store.subscriptions.find(x=>x.id===q.params.id);if(!x)return s.status(404).json({error:"الاشتراك غير موجود"});x.active=!!q.body.active;save();s.json(x)});
app.get("/api/owner/settings",auth,owner,(q,s)=>s.json(store.settings));
app.patch("/api/owner/settings",auth,owner,(q,s)=>{store.settings.announcement=String(q.body.announcement||"");store.settings.announcementColor=String(q.body.announcementColor||"#ff9cde");save();s.json(store.settings)});
app.patch("/api/owner/questions",auth,owner,(q,s)=>{store.settings.questions=Array.isArray(q.body.questions)?q.body.questions:[];save();s.json({questions:store.settings.questions})});
app.get("/api/admin/groups",auth,owner,(q,s)=>s.json({groups:store.groups}));
app.use(express.static(path.join(__dirname,"public")));
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("MLD Community listening on",PORT));
